### ISSUE TITLE
error: package directory 'smartagent' does not exist 

### ISSUE THREAD

**Issue by sebastianmacias** [jamespacileo/django-smartagent#3]
It seems like you didn't include the actual app 'smartagent'. Just wanted to let you know.

**Comment by jamespacileo** [comment]
thanks for raising this, I have just changed the package name from django_smartagent to smartagent.

Try reinstalling the package from latest version, and it should update the package name in your site-packages folder.

Only problem I found was a missing data file in MANIFEST.in, which I fixed.

**Comment by jamespacileo** [comment]
just realized you meant included in the repository... fixed that now. :)
