### ISSUE TITLE
middleware exception when HTTP_USER_AGENT doesn't exist

### ISSUE THREAD

**Issue by brightvalve** [jamespacileo/django-smartagent#4]
The middleware assumes that HTTP_USER_AGENT is always present in request.META, which isn't always the case (I regularly test with a CLI utility which doesn't send a User-Agent header; also, the Django test client - django.test.client.Client - doesn't either).

**Comment by jamespacileo** [comment]
thanks for raising this good catch, I guess I would have to fix this asap and also need a change of strategy for setting values when header is not present.

**Comment by jamespacileo** [comment]
I reckon this is fixed
